apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: atcb8yyuq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: atcb8yyuq-go 
  name: atcb8yyuq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: atcb8yyuq-go 
